# |-------------------------------------------------------------------------------
# | Nodeserver Copyright © 2021 rvnrstnsyh All Rights Reserved
# |-------------------------------------------------------------------------------
# |
# | Author    : Rivane Rasetiansyah <re@rvnrstnsyh.dev> (https://rvnrstnsyh.dev)
# | GitHub    : https://github.com/rvnrstnsyh
# | GitLab    : https://gitlab.com/rvnrstnsyh
# |

GET http://localhost:3000

###

GET http://localhost:3000/sign_up
